version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      # 패스워드같은 민감정보는 별도 파일로 마운트하여 사용할 수 있지만 해당 사전과제에서는 별도 마운트 한 서버를 제출할 수 없기에 암호화하지 않았습니다.
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: payhere
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - 6379:6379

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payhere?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started